version: "2.2"
services:
  slides:
    build:
      dockerfile: slides.Dockerfile
      context: .
    volumes:
      - "$PWD/slides.md:/app/slides.md"
    ports:
      - 8000:8000
  database:
    image: postgres
  webapp:
    build:
      context: .
    ports:
      - 80:8000
    entrypoint: python
    command:
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8000"
  jaeger:
    image: jaegertracing/all-in-one:1.6
    env:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 8080:16686
      - 14268:14268
      - 9411:9411
