version: "2.2"
services:
  generate-website-configs:
    image: hairyhenderson/gomplate
    env_file: .env
    volumes:
      - "$PWD/conf:/conf"
    working_dir: /conf
    command:
      - "--file"
      - website.yaml.tmpl
      - "--out"
      - website.yaml
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: polls
      POSTGRES_PASSWORD: polls
      POSTGRES_DB: polls_app
    volumes:
      - "$PWD/.dbdata:/var/lib/postgresql/data"
    ports:
      - 5432
  jaeger:
    image: jaegertracing/all-in-one:1.6
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 8080:16686
      - 5775/udp
      - 6831/udp
      - 6832/udp
      - 5778
      - 14268
      - 9411
  django:
    build:
      context: .
    entrypoint: python
    env_file: .env
    volumes:
      - "$PWD/app:/app"
      - "$PWD/conf:/conf"
    working_dir: /app
    command:
      - "-m"
      - django
      - "--version"
  website:
    depends_on:
      - generate-website-configs
      - jaeger
      - database
    extends: django
    ports:
      - 80:8000
    command:
      - manage.py
      - runserver
      - 0.0.0.0:8000
  slides:
    build:
      dockerfile: slides.Dockerfile
      context: .
    volumes:
      - "$PWD/slides.md:/app/slides.md"
    ports:
      - 8000:8000
